### ISSUE TITLE
Error converting network layer with mean operation

### ISSUE THREAD

**Issue by genp** [onnx/onnx-coreml#367]
I'm trying to convert a layer which uses a simple mean function as the last step in the forward function.  I'm getting this error during conversion. Without the mean I have no problems. Any thoughts?

```
TypeError: Error while converting op of type: ReduceMean. Error message: Unable to translate axes attribute to CoreML axis parameter for range(0, 4)
```

**Comment by aseemw** [comment]
Can you inspect the onnx model using Netron and check the values of the [attributes](https://github.com/onnx/onnx/blob/master/docs/Operators.md#reducemean) if the op "ReduceMean" ?

It looks like those attributes are not supported by CoreML.
Since its the last op, one workaround is to convert till the penultimate op (there might be some way to edit the onnx model to remove the last op, since its all protobuf).

**Comment by bhushan23** [comment]
@genp could you please give a try to https://github.com/onnx/onnx-coreml#new-beta-onnx-coreml-converter-with-core-ml-3 latest beta?
Feel free to re-open if you still face this issue

**Comment by genp** [comment]
Thanks! Will do.
