### ISSUE TITLE
issue about preprocessing image 

### ISSUE THREAD

**Issue by yizhaoyanbo** [onnx/onnx-coreml#393]
With pytorch model, the input image should be preprocessed. the steps include normalizing to 0-1,  subtracting r， g， b mean value， dividing std. But the convert function don't have proper arguments to do the dividing std step. How can I deal with it?  Thanks very much.

**Comment by aseemw** [comment]
If these operations are part of the graph itself, i.e. part of the onnx graph, then they should convert as well.

**Comment by yizhaoyanbo** [comment]
These operations are not part of the graph. I have followed this paper to do the preprocessing. But I have no idea to do the dividing step after the substracting step with the convert function.
 https://machinethink.net/blog/help-core-ml-gives-wrong-output/

**Comment by aseemw** [comment]
Its not that difficult to build an mlmodel from scratch, since its a protobuf format. See: https://github.com/apple/coremltools/blob/master/docs/APIExamples.md#building-an-mlmodel-from-scratch-using-neural-network-builder

This is what the converter does, collects the layers from onnx graph and converts them one by one to CoreML layers, in this for loop:https://github.com/onnx/onnx-coreml/blob/604c084801fd85616d2e443a0f3be70948d9965d/onnx_coreml/converter.py#L461

You could either:
- write a tiny mlmodel that does the pre-processing, followed by the main model (you could use layers such as MVN, reduce etc, list is [here](https://apple.github.io/coremltools/coremlspecification/sections/NeuralNetwork.html) and [here](https://github.com/apple/coremltools/blob/master/coremltools/models/neural_network/builder.py))
OR
- edit the onnx-converter to first add the layers corresponding to the pre-processing followed by the onnx graph

**Comment by OneDirection9** [comment]
hi, @yizhaoyanbo ,

#338  is a reference that use the `preprocessing_args` to do the preprocess.

**Comment by yizhaoyanbo** [comment]
@OneDirection9  thanks.

**Comment by bhushan23** [comment]
Looks like question has been answered
@yizhaoyanbo feel free to re-open if you have more questions
